// Generated by scripts/sync-design-tokens.mjs from docs/design-handoff/current/tokens.json.
// Edit the source, then regenerate.
export const DesignTokens = {
  "$schema": "weddingpick-design-tokens/1.0",
  "project": "웨딩픽 (WeddingPick)",
  "version": "3.10",
  "updated": "2026-09-04",
  "note": "SEED Design System (Karrot) 기반. Primary만 웨딩픽 코랄로 교체. 값은 모두 확정값이며 임의로 바꾸지 않는다.",
  "color": {
    "brand": {
      "primary": "#FF6F61",
      "primaryPressed": "#EE6255",
      "primaryDark": "#C2453A",
      "primaryTint": "#FFE8E4",
      "primarySurface": "#FFF5F2",
      "primaryBorder": "#FFD9D4"
    },
    "text": {
      "primary": "#212124",
      "secondary": "#393A40",
      "tertiary": "#4D5159",
      "quaternary": "#868B94",
      "disabled": "#ADB1BA",
      "onPrimary": "#FFFFFF"
    },
    "surface": {
      "paper": "#FFFFFF",
      "recessed": "#F7F8FA",
      "band": "#F2F3F6",
      "imagePlaceholder": "#EAEBEE",
      "canvas": "#EEF1F4",
      "inverse": "#0E0F10"
    },
    "line": {
      "border": "#DCDEE3",
      "divider": "#EAEBEE",
      "fieldBorder": "#D1D3D8",
      "fieldBorderFocus": "#212124"
    },
    "status": {
      "successText": "#1AA174",
      "successSurface": "#E8FAF6",
      "warningText": "#805217",
      "warningSurface": "#FFE3BA",
      "dangerText": "#E81607",
      "dangerSurface": "#FFE5E3",
      "dangerAction": "#FF4133",
      "accentText": "#0077B2",
      "accentAction": "#0088CC",
      "accentSurface": "#EBF7FA"
    },
    "overlay": {
      "dim": "rgba(0,0,0,.45)",
      "scrim": "rgba(0,0,0,.20)",
      "imageGradient": "linear-gradient(to top,rgba(0,0,0,.42),rgba(0,0,0,0) 58%)",
      "pillOnImage": "rgba(0,0,0,.5)"
    },
    "chart": {
      "series1": "#FF6F61",
      "series2": "#FFB3AB",
      "series3": "#FFD6D1",
      "seriesRest": "#EAEBEE"
    }
  },
  "skin": {
    "note": "사용자가 MY · 화면 설정에서 고른다. CTA · Pick · 선택 상태에만 적용된다. 앱 아이콘과 스플래시는 스킨과 무관하게 coral 고정.",
    "options": {
      "coral": "#FF6F61",
      "red": "#FF4D4D",
      "yellow": "#FFC041",
      "green": "#34C759",
      "blue": "#3182F6",
      "darkGray": "#191F28"
    },
    "default": "coral",
    "rule": "darkGray 선택 시 Pick 버튼만 coral을 유지한다. 회색 CTA는 비활성으로 읽히기 때문이다.",
    "unaffected": [
      "status.*",
      "앱 아이콘",
      "스플래시",
      "차트 계열색"
    ]
  },
  "typography": {
    "fontFamily": "-apple-system, BlinkMacSystemFont, system-ui, 'Apple SD Gothic Neo', 'Malgun Gothic', 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
    "webfont": null,
    "webfontNote": "웹폰트를 넣지 않는다. 시스템 서체를 쓴다.",
    "numeric": "tabular-nums",
    "scale": {
      "display": {
        "fontSize": 32,
        "lineHeight": 43,
        "fontWeight": 700,
        "use": "홈 Hero · 큰 금액"
      },
      "title": {
        "fontSize": 26,
        "lineHeight": 35,
        "fontWeight": 700,
        "use": "화면 제목"
      },
      "heading": {
        "fontSize": 24,
        "lineHeight": 32,
        "fontWeight": 700,
        "use": "시트 제목"
      },
      "section": {
        "fontSize": 20,
        "lineHeight": 27,
        "fontWeight": 700,
        "use": "섹션 제목 · 업체명"
      },
      "body": {
        "fontSize": 18,
        "lineHeight": 24,
        "fontWeight": [
          700,
          400
        ],
        "use": "리스트 행 이름"
      },
      "sub": {
        "fontSize": 16,
        "lineHeight": [
          22,
          24,
          26
        ],
        "fontWeight": [
          700,
          400
        ],
        "use": "본문 · 금액 · 버튼"
      },
      "caption": {
        "fontSize": 14,
        "lineHeight": [
          19,
          21
        ],
        "fontWeight": [
          700,
          400
        ],
        "use": "메타 · 건수 · 섹션 소제목"
      },
      "micro": {
        "fontSize": 13,
        "lineHeight": 18,
        "fontWeight": 700,
        "use": "배지"
      }
    },
    "lineClamp": {
      "listName": 1,
      "listMeta": 1,
      "amount": 1,
      "heroTitle": 2,
      "heroSub": 1,
      "cardTitle": 2,
      "cardBody": 1,
      "noticeBody": 2
    }
  },
  "spacing": {
    "gutter": 24,
    "sectionBottom": 28,
    "sectionGap": 24,
    "bandHeight": 16,
    "grid2Gap": 11,
    "grid2RowGap": 20,
    "grid3Gap": 10,
    "chipGap": 8,
    "rowGap": 2,
    "inlineGap": 12,
    "iconTextGap": 10
  },
  "size": {
    "screen": {
      "width": 390,
      "height": 844
    },
    "statusBar": 44,
    "header": 56,
    "headerSearch": 60,
    "tabBar": 72,
    "dock": 92,
    "rowMinHeight": 56,
    "rowMinHeightCompact": 48,
    "field": 52,
    "textarea": 88,
    "chip": 36,
    "chipLarge": 38,
    "toggle": {
      "width": 52,
      "height": 32,
      "knob": 26
    },
    "checkbox": 24,
    "avatar": {
      "small": 22,
      "row": 32,
      "profile": 56,
      "large": 88
    },
    "thumb": {
      "list": 52,
      "candidate": 44,
      "gallery": 52
    },
    "icon": {
      "tab": 24,
      "nav": 24,
      "inline": 18,
      "small": 14,
      "row": 20
    },
    "cta": {
      "primary": 52,
      "secondary": 48,
      "inCard": 44,
      "small": 40,
      "admin": 40
    },
    "backButton": 40
  },
  "safeArea": {
    "note": "시안의 statusBar 44 · tabBar 72는 iPhone 노치 기준값이다. 실기기에서는 inset을 더한다.",
    "formula": {
      "tabBar": "72 + max(safeBottom, 0)",
      "dock": "92 + max(safeBottom, 0)",
      "sheetBottomPadding": "28 + max(safeBottom, 0)",
      "statusBar": "safeTop"
    },
    "reference": {
      "iosNotch": {
        "safeTop": 44,
        "safeBottom": 34
      },
      "iosHome": {
        "safeTop": 20,
        "safeBottom": 0
      },
      "androidGesture": {
        "safeTop": "24~40",
        "safeBottom": "16~24"
      },
      "androidThreeButton": {
        "safeTop": "24~40",
        "safeBottom": 0,
        "systemBar": 48,
        "warning": "inset이 0으로 온다. edge-to-edge를 끄거나 WindowInsets를 직접 읽어야 한다."
      }
    },
    "rule": [
      "하단 고정 요소에만 inset을 더한다 — 탭바 · dock · 바텀시트.",
      "스크롤 내용에는 넣지 않는다. 넣으면 스크롤 끝에 빈 공간이 두 번 생긴다.",
      "34 · 18 · 48 같은 숫자를 상수로 박지 않는다. useSafeAreaInsets()의 값을 쓴다.",
      "폴더블과 태블릿에서 좌우 inset이 0이 아닐 수 있다. Gutter 24에 safeLeft · safeRight를 더한다."
    ]
  },
  "platform": {
    "letterSpacing": {
      "note": "안드로이드에서 자간을 넣지 않으면 글자가 벌어져 2줄 제목이 3줄로 터진다.",
      "ios": {
        "display": "0em",
        "title": "0em",
        "body": "0em",
        "caption": "0em"
      },
      "android": {
        "display": "-0.04em",
        "title": "-0.03em",
        "body": "-0.02em",
        "caption": "-0.04em"
      }
    },
    "font": {
      "ios": "Apple SD Gothic Neo",
      "android": "Roboto · Noto Sans KR"
    },
    "backButton": {
      "ios": "좌상단 화살표 + 좌측 스와이프",
      "android": "물리 버튼 · 제스처 — 화면마다 처리 필요",
      "rules": [
        {
          "when": "Root 5탭",
          "action": "앱을 닫는다. 홈 탭이 아니면 홈 탭으로 먼저 간다"
        },
        {
          "when": "바텀시트 열림",
          "action": "시트만 닫는다. 화면은 그대로 둔다",
          "required": true
        },
        {
          "when": "초기 설정 4단계 중",
          "action": "이전 단계로 간다. 첫 단계에서는 로그인으로",
          "required": true
        },
        {
          "when": "Pick 인증 진행 중",
          "action": "나가면 올린 자료가 사라진다고 묻는다"
        },
        {
          "when": "후기 작성 중 · 내용 있음",
          "action": "임시 저장할지 묻는다"
        },
        {
          "when": "검색 결과 · 업체 상세",
          "action": "이전 화면으로 간다"
        },
        {
          "when": "이미지 전체보기",
          "action": "상세로 돌아간다"
        },
        {
          "when": "결정 완료 · 연결 완료",
          "action": "뒤로 못 간다. 다음 화면으로만",
          "blocked": true
        }
      ]
    },
    "diff": {
      "screenTransition": {
        "ios": "오른쪽에서 밀려 들어옴",
        "android": "아래에서 올라오며 페이드"
      },
      "sheetDismiss": {
        "ios": "드래그 · 배경 탭",
        "android": "드래그 · 배경 탭 · 뒤로가기"
      },
      "permissionRetry": {
        "ios": "한 번 거부하면 설정으로만",
        "android": "두 번 거부하면 영구 차단"
      },
      "share": {
        "ios": "UIActivityViewController",
        "android": "Intent Chooser"
      },
      "haptic": {
        "ios": "Pick 성공 시 medium",
        "android": "기기별 지원 확인 후 적용"
      },
      "statusBarIcon": {
        "ios": "자동 반전",
        "android": "light · dark 직접 지정"
      }
    }
  },
  "auth": {
    "guestBrowsing": false,
    "note": "비회원 이용을 없앴다. 스플래시 다음이 바로 로그인이다.",
    "providers": [
      "카카오",
      "네이버",
      "구글",
      "애플"
    ],
    "primary": "카카오",
    "sheetOrder": [
      "네이버",
      "구글",
      "애플"
    ],
    "email": false,
    "kakaoBrand": {
      "bg": "#FEE500",
      "fg": "#191919"
    },
    "naverBrand": {
      "bg": "#03C75A",
      "fg": "#FFFFFF"
    },
    "appleBrand": {
      "bg": "#000000",
      "fg": "#FFFFFF"
    },
    "googleBrand": {
      "bg": "#FFFFFF",
      "fg": "#212124",
      "border": "#DCDEE3"
    }
  },
  "radius": {
    "badge": 4,
    "control": 6,
    "card": 10,
    "pickCard": 14,
    "sheet": 20,
    "phoneFrame": 40,
    "storeIcon": 26,
    "pill": 999
  },
  "border": {
    "hairline": 1,
    "selected": 1.5,
    "checkbox": 1.5,
    "focus": 2
  },
  "shadow": {
    "note": "그림자를 거의 쓰지 않는다. 구분은 inset 선과 배경 톤으로 한다.",
    "tabBarTop": "inset 0 1px 0 #EAEBEE",
    "dockTop": "inset 0 1px 0 #EAEBEE",
    "rowDivider": "inset 0 -1px 0 #EAEBEE",
    "outline": "inset 0 0 0 1px #EAEBEE",
    "floatingCard": "0 2px 6px rgba(0,0,0,.16)",
    "phoneFrame": "0 15px 75px rgba(0,27,55,.14)"
  },
  "motion": {
    "press": {
      "transform": "scale(0.97)",
      "duration": 100
    },
    "pressButton": {
      "transform": "scale(0.98)",
      "duration": 100
    },
    "sheetEnter": {
      "from": "translateY(100%)",
      "to": "translateY(0)",
      "duration": 350,
      "easing": "cubic-bezier(.16,1,.3,1)"
    },
    "checkPop": {
      "keyframes": "scale(0) → scale(1.18) → scale(1)",
      "duration": 460,
      "easing": "cubic-bezier(.34,1.56,.64,1)"
    },
    "ringSpread": {
      "keyframes": "scale(.5) opacity(.45) → scale(2.4) opacity(0)",
      "duration": 1000,
      "easing": "cubic-bezier(.16,1,.3,1)"
    },
    "rise": {
      "from": "translateY(10px) opacity(0)",
      "to": "translateY(0) opacity(1)",
      "duration": 420,
      "easing": "cubic-bezier(.16,1,.3,1)"
    },
    "riseDelays": [
      150,
      260,
      380
    ],
    "selectFill": {
      "property": "background",
      "duration": 150
    },
    "scanSweep": {
      "duration": 1600,
      "easing": "cubic-bezier(.4,0,.6,1)",
      "loop": true
    },
    "spinner": {
      "duration": 800,
      "easing": "linear",
      "loop": true
    },
    "skeletonPulse": {
      "keyframes": "opacity 1 → .45 → 1",
      "duration": 1400,
      "easing": "ease-in-out",
      "loop": true
    }
  },
  "image": {
    "crop": "center cover",
    "faceRule": "인물 얼굴이 잘리는 사진은 업체 제공이어도 쓰지 않고 다음 순위 이미지로 넘어간다.",
    "fallbackOrder": [
      "업체 제공",
      "사용 허가",
      "공공 · 공식",
      "업종 기본 이미지"
    ],
    "noPlaceholderText": "«사진 준비 중» 문구나 빈 상자를 노출하지 않는다. 업종 기본 이미지로 대체한다.",
    "specs": {
      "vendorHero": {
        "width": 390,
        "height": 260,
        "ratio": "3:2"
      },
      "vendorGalleryFull": {
        "width": 390,
        "height": 440,
        "ratio": "free"
      },
      "homeTodayPick": {
        "width": 342,
        "height": 196,
        "ratio": "16:9"
      },
      "searchResultCard": {
        "width": 342,
        "height": 168,
        "ratio": "2:1"
      },
      "expoHero": {
        "width": 390,
        "height": 220,
        "ratio": "16:9"
      },
      "feedCard2col": {
        "ratio": "16:11"
      },
      "feedCardSquare": {
        "ratio": "1:1"
      },
      "tasteCard": {
        "ratio": "1:1",
        "height": 150
      },
      "candidateThumb3col": {
        "width": 107,
        "height": 96
      },
      "listThumb": {
        "width": 52,
        "height": 52,
        "radius": 6
      },
      "galleryThumb": {
        "width": 52,
        "height": 52,
        "radius": 6
      }
    },
    "textOnImage": {
      "allowedScreens": [
        "vendorHero",
        "tasteCard"
      ],
      "requirement": "하단 어둠 그라데이션을 깔아 대비 4.5:1 확보"
    }
  },
  "symbol": {
    "name": "Pick Mark",
    "rule": "하트 안에 체크. 절대 변경 금지.",
    "viewBox": "0 0 24 24",
    "strokeWidth": 1.9,
    "strokeLinecap": "round",
    "strokeLinejoin": "round",
    "fill": "none",
    "paths": [
      "M12 20.5S3.5 15.2 3.5 9.9A4.4 4.4 0 0 1 12 8.1a4.4 4.4 0 0 1 8.5 1.8c0 5.3-8.5 10.6-8.5 10.6Z",
      "M9.4 11.9l1.7 1.7 3.4-3.4"
    ],
    "checkCenter": {
      "x": 12,
      "y": 11.9
    },
    "usage": [
      "앱 아이콘 5종",
      "스플래시",
      "시작 화면",
      "Pick 탭",
      "Pick 완료 모션",
      "웹 GNB",
      "관리자 로그인",
      "관리자 사이드바"
    ],
    "appIcon": {
      "background": "#FF6F61",
      "mark": "#FFFFFF",
      "note": "스킨과 무관하게 고정"
    }
  },
  "tabBar": {
    "height": 72,
    "paddingTop": 9,
    "itemMinHeight": 52,
    "iconSize": 24,
    "strokeWidth": 1.8,
    "labelSize": 12,
    "labelLineHeight": 16,
    "labelWeight": 700,
    "gap": 3,
    "activeColor": "#212124",
    "inactiveColor": "#868B94",
    "items": [
      {
        "id": "home",
        "label": "홈",
        "icon": "house"
      },
      {
        "id": "search",
        "label": "검색",
        "icon": "magnifier"
      },
      {
        "id": "pick",
        "label": "Pick",
        "icon": "pickMark"
      },
      {
        "id": "couple",
        "label": "우리웨딩",
        "icon": "twoPeople"
      },
      {
        "id": "my",
        "label": "MY",
        "icon": "person"
      }
    ]
  },
  "component": {
    "row": {
      "minHeight": 56,
      "paddingY": 12,
      "paddingYWithMeta": 14,
      "gap": 12,
      "divider": {
        "height": 1,
        "color": "#EAEBEE"
      },
      "align": "center · meta가 있으면 flex-start"
    },
    "badge": {
      "height": 22,
      "paddingX": 9,
      "paddingY": 4,
      "radius": 4,
      "fontSize": 14,
      "lineHeight": 19,
      "fontWeight": 700,
      "whiteSpace": "nowrap",
      "rule": "항상 한 줄. 아래로 내리지 않는다."
    },
    "chip": {
      "height": 36,
      "paddingX": 14,
      "radius": 999,
      "fontSize": 14,
      "fontWeight": 700,
      "activeBg": "#212124",
      "activeFg": "#FFFFFF",
      "inactiveBg": "#F2F3F6",
      "inactiveFg": "#4D5159",
      "overflow": "가로 스크롤 · flex:0 0 auto"
    },
    "card": {
      "radius": 10,
      "padding": 20,
      "paddingCompact": "18px 20px",
      "gap": 10,
      "defaultBg": "#FFFFFF",
      "defaultBorder": "1px solid #DCDEE3",
      "recessedBg": "#F7F8FA",
      "recessedBorder": "none",
      "brandBg": "#FFF5F2",
      "brandBorder": "1px solid #FFD9D4"
    },
    "sheet": {
      "radius": "20px 20px 0 0",
      "padding": "12px 24px 28px",
      "gap": 20,
      "grabber": {
        "width": 40,
        "height": 4,
        "radius": 999,
        "color": "#EAEBEE"
      },
      "backdrop": "rgba(0,0,0,.45)"
    },
    "field": {
      "height": 52,
      "radius": 6,
      "padding": "0 14px",
      "border": "1px solid #D1D3D8",
      "borderFocus": "1px solid #212124",
      "fontSize": 16,
      "placeholderColor": "#ADB1BA"
    },
    "progressTrack": {
      "height": 6,
      "radius": 999,
      "bg": "#EAEBEE",
      "fill": "#FF6F61"
    },
    "stackedBar": {
      "height": 10,
      "radius": 999,
      "bg": "#EAEBEE"
    },
    "twoColCard": {
      "gap": 11,
      "rowGap": 20,
      "imageRatio": "16:11",
      "textBlockHeight": 92,
      "ctaAlign": "margin-top:auto — 같은 행 CTA 하단선 일치",
      "lineClamp": {
        "name": 1,
        "amount": 1,
        "count": 1,
        "reason": 1
      }
    }
  },
  "grid": {
    "gutter": 24,
    "col2": "(390 - 48 - 11) / 2 = 165.5",
    "col3": "(390 - 48 - 20) / 3 = 107.3",
    "rule": [
      "동일 행 카드 폭과 내부 패딩을 통일한다.",
      "이미지 비율을 동일하게 한다.",
      "같은 행 CTA의 Y축을 맞춘다.",
      "제목 · 메타 · 설명의 최대 줄 수를 지정한다.",
      "이유 없는 몇 px짜리 오프셋을 만들지 않는다.",
      "가로 Carousel과 Full-bleed 이미지만 예외이며 첫 콘텐츠 시작선은 24px에 맞춘다."
    ]
  }
} as const;
